microlise_survey_homepage:
    path:     /
    defaults: { _controller: MicroliseSurveyBundle:Survey:index }

microlise_survey_create:
    path:     /create
    defaults: { _controller: MicroliseSurveyBundle:Survey:create }
