microlise_survey_homepage:
    path:     /
    defaults: { _controller: MicroliseSurveyBundle:Survey:index }

microlise_survey_create:
    path:     /create
    defaults: { _controller: MicroliseSurveyBundle:Survey:create }

microlise_survey_create_question:
    path:     /create/questions
    defaults: { _controller: MicroliseSurveyBundle:Survey:question }

microlise_survey_confirm:
    path:     /create/confirm
    defaults: { _controller: MicroliseSurveyBundle:Survey:confirm }

microlise_survey_display:
    path:     /{id}/view
    defaults: { _controller: MicroliseSurveyBundle:Survey:display }

microlise_survey_edit:
    pattern: /{id}/edit
    defaults: { _controller: MicroliseSurveyBundle:Survey:edit }

microlise_survey_delete:
    pattern: /{id}/delete
    defaults: { _controller: MicroliseSurveyBundle:Survey:delete }

